### ISSUE TITLE
Nothing happen when configuring auto assign

### ISSUE THREAD

**Issue by deda9** [kentaro-m/auto-assign#101]
I've checked this bug #63 but it didnt work as well.

I am already facing the same problem I already installed the bot into out private repository with:
```yml
addReviewers: true
# Enable to add reviewers as assignees.
addAssignees: true

reviewers: 
  - deda9

skipKeywords:
  - wip

numberOfReviewers: 0
```
but we didnt merge this into our master branch yet, might be that the problem?
