### ISSUE TITLE
Cannot find the actions on github CI

### ISSUE THREAD

**Issue by tanphamhaiduong** [kentaro-m/auto-assign#116]
**Describe the bug**
I have already config as the doc but still not find actions when run CI
```
addReviewers: true
addAssignees: author
numberOfReviewers: 0
numberOfAssignees: 1
useReviewGroups: true
reviewGroups:
  groupA:
    - tanphamhaiduong
useAssigneeGroups: false
```
```
...
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  CI: true
...
add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

**Expected behavior**
It can find actions

**Screenshots**
![image](https://user-images.githubusercontent.com/22660833/72508673-b1e49500-3878-11ea-8c6e-49d6971ce740.png)
