### ISSUE TITLE
Auto Assign Bot Randomly fails to assign a reviewer or two

### ISSUE THREAD

**Issue by osquitoOfTheNorth** [kentaro-m/auto-assign#117]
**Describe the bug**

Sometimes with some pull requests, auto-assign will assign two reviewers when three are requested. We also maintain two groups. 

**To Reproduce**
1.Add the auto-assign GitHub app to a repo.
2.Submit a PR against the repo.
3.Sometimes auto-assign will assign two reviewers, sometimes it will fail to assign any at all.

**Expected behavior**
Assignment of all 3 reviewers should always happen consistently. 

**Additional context**
A sample .yml file that closely mirrors our github repo setup.

```
addReviewers: true

numberOfReviewers: 1

useReviewGroups: true
reviewGroups:
  groupA:
    - user1
    - user2
  groupB:
    - user3
    - user4
    - user5
  groupC:
    - user6
    - user7
    - user8
    - user9
```
