### ISSUE TITLE
Auto-Assign based on changes

### ISSUE THREAD

**Issue by hitmands** [kentaro-m/auto-assign#118]
**Is your feature request related to a problem? Please describe.**
It is normally the case, while working with monorepos, for multiple teams to own the same codebase but work on different packages (e.g. lerna, yarn workspaces, etc.). **It'd be great to provide some support for these use cases** where a group would be assigned to a pr if a specific glob matches.

**Describe the solution you'd like**
Extend the [`group`](https://github.com/kentaro-m/auto-assign#multiple-reviewers-list) feature so that if a specific glob produces matches then the group is requested a review.

```yml
useReviewGroups: true

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
reviewGroups:
  groupA:
    - reviewerA
    - reviewerB
    - reviewerC
  groupB:
    - reviewerD
    - reviewerE
    - reviewerF

paths:
  groupA: 
    - "./packages/pkg-a/**/*.*"
    - "./glob/for/shared/files"

  groupB: 
    - "./packages/pkg-b/**/*.*"
    - "./glob/for/shared/files"
```

**Additional context**
In the given example, 
if a change happens on `./packages/pkg-a/**/*.`, then we would assign `groupA`;
if a change happens on `./packages/pkg-b/**/*.`, then we would assign `groupB`;
if a change happens on `/glob/for/shared/files`, then we would assign both `groupA` and `groupb`;

----

I'd like to investigate a propose a pull request to implement it.
