### ISSUE TITLE
Assignment based on words

### ISSUE THREAD

**Issue by Dgame** [kentaro-m/auto-assign#131]
**Is your feature request related to a problem? Please describe.**
In a project with many developers in different teams for different parts of the project it is difficult/impossible to use `auto_assign`.

**Describe the solution you'd like**
Assignment of teams/people based on words in the title of the PR. For example:
```yml
reviewWordGroups:
    - words: ['security', 'secure']
      reviewer: ['org/security', 'org/devop']
    - words: ['tests']
      reviewer: ['org/testing']
```

**Describe alternatives you've considered**

**Additional context**
