### ISSUE TITLE
Auto-assign PR to author not working

### ISSUE THREAD

**Issue by Habitats** [kentaro-m/auto-assign#141]
**Describe the bug**
Auto-assignment on PR not working anymore. It used to work, and without any config changes it just stopped.

This is our config:
```
addReviewers: false
addAssignees: author
skipKeywords:
  - wip
numberOfReviewers: 0
```
**To Reproduce**
1. Open PR

**Expected behavior**
Author should be assigned to PR.

**Comment by dirien** [comment]
I can confirm this too!

**Comment by jonasbn** [comment]
I just tried with the following `.github/auso_assign.yml` and it worked:

```yaml
# REF: https://probot.github.io/apps/auto-assign/

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: 'author'

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - jonasbn

# A list of keywords to be skipped the process that add reviewers if pull requests include it
#skipKeywords:
#  - wip

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

# A list of assignees, overrides reviewers if set
# assignees:
#  - jonasbn

# A number of assignees to add to the pull request
# Set to 0 to add all of the assignees.
# Uses numberOfReviewers if unset.
# numberOfAssignees: 2
```

Note that I have quoted the keyword author. I look at the code, which either takes a `boolean` or a `string`, so I thought I might as well try it.

First attempt was unsuccessful, since I only pushed the branch, the assignment was not made until the PR was created, which happened second time I tried.

See [the PR](https://github.com/jonasbn/til/pull/27) for details.
