### ISSUE TITLE
numberOfAssignees is overwritten by numberOfReviewers when 0 is set

### ISSUE THREAD

**Issue by koyama-yoshihito** [kentaro-m/auto-assign#177]
**Describe the bug**
When `numberOfAssignees` is set to 0, it is overwritten by the value of `numberOfReviewers`

**To Reproduce**
Create an auto_assign.yml like this, and place it in a GitHub repository.
```yml
addReviewers: true
addAssignees: true

reviewers:
  - reviewerA
  - reviewerB
  - reviewerC

numberOfReviewers: 2

assignees:
  - assigneeA
  - assigneeB

numberOfAssignees: 0
```

**Expected behavior**
Assignee is assumed to be everyone, but only 2 assignees were set.
Meanwhile, reviewers were properly set to 2 as I intended.

**Causes**
According to my research, these lines cause this issue.
https://github.com/kentaro-m/auto-assign/blob/9c0678cf0b61cfdb49487c3ca8db96c425cfae91/src/util.ts#L116
https://github.com/kentaro-m/auto-assign/blob/9c0678cf0b61cfdb49487c3ca8db96c425cfae91/src/util.ts#L122
When `numberOfAssignees` is 0, it is overwritten by `numberOfReviewers`.

I think this issue will be fixed if we rewrite like this.

```javascript
numberOfAssignees ?? numberOfReviewers
```
or
```javascript
numberOfAssignees === 0 ? 0 : numberOfAssignees || numberOfReviewers
```
I hope it works well.

**Desktop (please complete the following information):**

I don't think the local environment matters this issue.
 - OS: macOS
 - Browser:  Chrome
 - Version: latest version (chrome)
