### ISSUE TITLE
Option(numberOfReviewers) does not work properly

### ISSUE THREAD

**Issue by comeonyo** [kentaro-m/auto-assign#239]
**Describe the bug**
I set auto_assign.yml as below.
The Bot assign only one reviewer from the list.
If i set numberOfReviewers as 2, the bot assign 2 reviewers, as i expected.

```yaml
# Set to true to add assignees to pull requests
addAssignees: author

# Set to true to add reviewers to pull requests
addReviewers: true

reviewers:
  - userA
  - userB

```

**Expected behavior**
Assign all reviewers.
