### ISSUE TITLE
auto_assign.yml not working, I don't know the problem ...

### ISSUE THREAD

**Issue by yhhwangserver** [kentaro-m/auto-assign#252]
**Describe the bug**
* Installed GitHup App -> Auto Assign
* Access is Approved
* Add .github/auto_assign.yml
* Request PR

```yml
# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: author

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
 - younsoo-kim
 - YoungChulShin-Russel
 - p829911
 - daeyorkim
 - sunghoonkim0
 - onacit
 - yhhwangserver

# A list of keywords to be skipped the process that add reviewers if pull requests include it
skipKeywords:
 - wip

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0
```

auto-assign bot is not working. 
So I added reviewers and assignees manulay.
How can I fix it?

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome
