### ISSUE TITLE
Nothing happen when configuring auto assign

### ISSUE THREAD

**Issue by clakech** [kentaro-m/auto-assign#63]
**Describe the bug**
I enable auto assign, but it does not work on any pull requests

**To Reproduce**
1. enable auto-assign following documentation
2. configure .github/auto_assign.yml

```
addReviewers: true

addAssignees: false

reviewers: 
  - clakech

skipKeywords:
  - wip

numberOfReviewers: 0
```

**Expected behavior**
Auto assign should auto assign clakech to the newly created pull requests

**Screenshots**
Auto assign is configured with above config file .github/auto_assign.yml
<img width="785" alt="capture d ecran 2019-02-08 a 11 36 49" src="https://user-images.githubusercontent.com/1169286/52473358-de3a6080-2b95-11e9-971d-430b703a4dbd.png">

**Additional context**
private repository

**Comment by kentaro-m** [comment]
@clakech 
Thank you for using my GitHub app. It is unable to request a review from the pull request owner on the specification of GitHub.
https://developer.github.com/v3/pulls/review_requests/#create-a-review-request

I want you to use the function that adds assignees with the following: 
```yaml
addReviewers: false
# Enable to add as assignees.
addAssignees: true

reviewers: 
  - clakech

skipKeywords:
  - wip

numberOfReviewers: 0
```

**Comment by clakech** [comment]
Thanks

**Comment by deda9** [comment]
Hello guys @clakech @kentaro-m 

We are already facing the same problem We already installed the bot into out private repository with:
```yml
addReviewers: false
# Enable to add reviewers as assignees.
addAssignees: true

reviewers: 
  - deda9

skipKeywords:
  - wip

numberOfReviewers: 0
```
but we didnt merge this into our master branch, might be that the problem?
