### ISSUE TITLE
Ability to get asignees/reviewers from OWNERS file

### ISSUE THREAD

**Issue by haiker2011** [kentaro-m/auto-assign#85]
**Is your feature request related to a problem? Please describe.**
now, many repo already have the OWNERS file in the repo,include the people who can review. now we only can add reviewer by auto_assign.yml,can auto_assign.yml to read OWNERS file get the reviewer ?

**Describe the solution you'd like**
auto_assign.yml to read OWNERS file get the review people.
for example , auto_assign.yml
```yaml
# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - OWNERS # the file path and name

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 0

# A list of assignees, overrides reviewers if set
# assignees:
#   - assigneeA

# Set to true to add reviewers from different groups to pull requests
# useReviewGroups: true

# A list of reviewers, split into different groups, to be added to pull requests (GitHub user name)
# reviewGroups:
#   groupA:
#     - user1
#   groupB:
#     - user2
```
