### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by littleStudent** [kentaro-m/auto-assign#99]
**Describe the bug**
When running the prebuilt action i get the following error:

```
07:30:12.168Z ERROR event: Cannot read property 'length' of undefined (id=....)
  TypeError: Cannot read property 'length' of undefined
      at Object.chooseUsers (/app/lib/util.js:9:20)
      at /app/lib/handler.js:57:40
      at step (/app/lib/handler.js:32:23)
      at Object.next (/app/lib/handler.js:13:53)
      at fulfilled (/app/lib/handler.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  --
  event: {
    "event": "pull_request.opened",
    "id": "....",
    "repository": "..."
  }
```

Config:
```yaml
# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 3

# Set to true to add reviewers from different groups to pull requests
useReviewGroups: false

reviewers:
  - userA
  - userB
  - userC


# Set to true to add assignees from different groups to pull requests
useAssigneeGroups: false

```

**To Reproduce**
Sadly its a private repo and i am not sure how to reproduce this. If you cant help with the provided information plz let me know. I will try to create a public repo to showcase the error 

**Expected behavior**
With the provided config this should simply work
